[package]
name = "bevy-testing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6.1"
bevy_prototype_lyon = "0.4.0"
pathfinding = "3.0.10"
itertools = "0.10.3"
# image = "0.24.1"
rand = "0.8.5"
rand_distr = "0.4.3"